#!/usr/bin/env python2.7

import sys
import json
from feeding.playerState import *
from feeding.player import *

testInput = []
try:
    testInput = json.load(sys.stdin)
    if len(testInput) == 3:
        curState, wateringHole, otherPlayers = PlayerState.parse_feeding(testInput)
        player = Player(curState.id)
        result = player.feedNext(curState, wateringHole, otherPlayers).to_json()

        sys.stdout.write(json.dumps(result))

except Exception as e:
    quit()


