MAX_TRAITS = 3
WATERING_HOLE_FOOD = 1
MAX_CARDS = 122
CARDS_PER_TURN = 3
MAX_CARNIVORE_TRAITS = 17
MAX_OTHER_TRAITS = 7
NUM_CARDS_FOR_EXTINCTION = 2
CARNIVORE_UPPER_BOUND = 8
CARNIVORE_LOWER_BOUND = -8
TRAIT_UPPER_BOUND = 3
TRAIT_LOWER_BOUND = -3
MIN_PLAYERS = 3
MAX_PLAYERS = 8

# TRAIT CARD NAMES
CARNIVORE = "carnivore"
WARNING_CALL = "warning-call"
AMBUSH = "ambush"
BURROWING = "burrowing"
CLIMBING = "climbing"
HARD_SHELL = "hard-shell"
PACK_HUNTING = "pack-hunting"
HORNS = "horns"
HERDING = "herding"
SYMBIOSIS = "symbiosis"
FAT_TISSUE = "fat-tissue"
COOPERATION = "cooperation"
FERTILE = "fertile"
FORAGING = "foraging"
LONG_NECK = "long-neck"
SCAVENGER = "scavenger"

TRAIT_TYPES = [CARNIVORE, WARNING_CALL, AMBUSH, BURROWING, CLIMBING, HARD_SHELL, PACK_HUNTING, HORNS, HERDING,
               SYMBIOSIS, FAT_TISSUE, COOPERATION, FERTILE, FORAGING, LONG_NECK, SCAVENGER]

# JSON Labels
FOOD_LABEL = "food"
BODY_LABEL = "body"
POPULATION_LABEL = "population"
TRAITS_LABEL = "traits"
FAT_FOOD_LABEL = "fat-food"
ID_LABEL = "id"
SPECIES_LABEL = "species"
BAG_LABEL = "bag"
CARDS_LABEL = "cards"

# GUI Display Constants
DISPLAY_WIDTH = 500
DISPLAY_HEIGHT = 750

# TCP Constants
MESSAGE_SIZE = 16384
OK_MESSAGE_LENGTH = 4
SERVER_HOST = '0.0.0.0'
PORT = 5999
SIGNUP_WINDOW = 20
TIMEOUT = 5
BACKLOG = 5
START_MSG_LENGTH = 4
CHOOSE_MSG_LENGTH = 2
FEED_MSG_LENGTH = 5
OK = 'ok'